apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      mylabel: c34

  template:
    spec:
      containers:
      - name: nginx
        image: nginx
    metadata:
     labels:
        mylabel: c34