apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      batch: c34
  template:
    metadata:
      labels:
        batch: c34
    spec:
      containers:
      - name: nginx
        image: nginx